name: Journey
version: 0.0.0-beta
main: edu.whimc.journey.spigot.JourneySpigot
api-version: 1.17
authors:
  - pietelite
description: A path-optimization Minecraft solution
website: https://whimcproject.web.illinois.edu/
softdepend:
  - WHIMC-Portals
  - Quests
permissions:
  journey.journey:
    default: false
    description: Root command for journey subcommands
  journey.debug:
    default: false
    description: Turn on debug mode
  journey.nav:
    default: false
  journey.nav.use:
    default: false
    description: Allows the use of trails
  journey.nav.manage:
    default: false
    description: Allows the management of trails
commands:
  journey:
    description: Root Journey command
  nav:
    description: Shows a player a trail to their destination
  endpoint:
    description: Sets an endpoint for a player's trail


