name: Indicator
version: @version@
main: edu.whimc.indicator.Indicator
api-version: 1.16
authors: [ pietelite ]
description: A path indication plugin
website: https://whimcproject.web.illinois.edu/
softdepend:
  - WHIMC-Portals
permissions:
  indicator.indicator:
    default: true
    description: Root command for indicator subcommands
  indicator.debug:
    default: false
    description: Turn on debug mode
  indicator.trail:
    default: true
    description: Allows the use of the trail command
  indicator.destination:
    default: false
    description: Allows the use of the description sub command
commands:
  indicator:
    description: Root indicator command
  trail:
    description: Shows a player a trail to their destination
  endpoint:
    description: Sets an endpoint for a player's trail


