name: Indicator
version: 0.0.0
main: edu.whimc.indicator.spigot.Indicator
api-version: 1.17
authors:
  - pietelite
description: A path indication plugin
website: https://whimcproject.web.illinois.edu/
softdepend:
  - WHIMC-Portals
  - Quests
permissions:
  indicator.indicator:
    default: false
    description: Root command for indicator subcommands
  indicator.debug:
    default: false
    description: Turn on debug mode
  indicator.nav:
    default: false
  indicator.nav.use:
    default: false
    description: Allows the use of trails
  indicator.nav.manage:
    default: false
    description: Allows the management of trails
commands:
  indicator:
    description: Root indicator command
  nav:
    description: Shows a player a trail to their destination
  endpoint:
    description: Sets an endpoint for a player's trail


